// <auto-generated />
using System;
using EquipmentBorrowing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentBorrowing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EquipmentBorrowingDbContext))]
    [Migration("20260929152008_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.Property<string>("BorrowId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BorrowId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId", "Status");

                    b.HasIndex(new[] { "EquipmentId" }, "IX_Borrowings_EquipmentId");

                    b.HasIndex(new[] { "EquipmentId" }, "UX_Borrowings_EquipmentId_Active")
                        .IsUnique()
                        .HasFilter("Status = 0");

                    b.ToTable("Borrowings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Borrowings_BorrowId_NotBlank", "length(trim(BorrowId)) > 0");

                            t.HasCheckConstraint("CK_Borrowings_ReturnDate", "ReturnDate > BorrowDate");

                            t.HasCheckConstraint("CK_Borrowings_ReturnedAt", "ReturnedAt IS NULL OR ReturnedAt >= BorrowDate");

                            t.HasCheckConstraint("CK_Borrowings_Status", "Status IN (0, 1)");

                            t.HasCheckConstraint("CK_Borrowings_Status_ReturnedAt", "(Status = 0 AND ReturnedAt IS NULL) OR (Status = 1 AND ReturnedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Equipment", b =>
                {
                    b.Property<string>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivelyBorrowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Equipment_EquipmentId_NotBlank", "length(trim(EquipmentId)) > 0");

                            t.HasCheckConstraint("CK_Equipment_IsActivelyBorrowed", "IsActivelyBorrowed IN (0, 1)");

                            t.HasCheckConstraint("CK_Equipment_Name_NotBlank", "length(trim(Name)) > 0");

                            t.HasCheckConstraint("CK_Equipment_Type_NotBlank", "length(trim(Type)) > 0");
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Students_IsAuthorized", "IsAuthorized IN (0, 1)");

                            t.HasCheckConstraint("CK_Students_Name_NotBlank", "length(trim(Name)) > 0");

                            t.HasCheckConstraint("CK_Students_Program_NotBlank", "length(trim(Program)) > 0");

                            t.HasCheckConstraint("CK_Students_StudentId_NotBlank", "length(trim(StudentId)) > 0");
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.HasOne("EquipmentBorrowing.Domain.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EquipmentBorrowing.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
